aws/language-server-runtimes

- package-lock.json
- runtimes/package.json
- types/CHANGELOG.md
- types/package.json
We want to release a new version of types package 
Change version and update Changelog
> Upgrade types version to 0.0.2

- package-lock.json
- runtimes/package.json
Version 0.0.1 of runtimes types is being consumed
Consume latest 
> Consume latest types package

- package-lock.json
Some NPM package versions cause issues internally
Use previous versions 
> Fix consumed versions

- types/CHANGELOG.md
- types/package.json
> Bum runtime-types minor version to 0.0.3

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
- package-lock.json
Bump chat-ui-types minor version
> Bump chat-ui-types minor version

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Releasing latest runtimes version
> Upgrade runtimes version to 0.2.5

- chat-client-ui-types/package.json
- package-lock.json
Types package consumed is outdated
Always consume latest types version
> Use latest types version for ui-types

- types/CHANGELOG.md
- types/package.json
> Upgrade types to 0.0.5

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Releasing new runtimes version
> Release runtimes version 0.2.6

- package-lock.json
- types/CHANGELOG.md
- types/package.json
> Release types 0.0.6

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Release runtimes version 0.2.7
> Release runtimes 0.2.7

- runtimes/runtimes/auth/standalone/encryption.test.ts
- runtimes/runtimes/auth/standalone/encryption.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/runtimes/chat/encryptedChat.test.ts
- runtimes/runtimes/chat/encryptedChat.ts
- runtimes/runtimes/standalone.ts
This is a followup to https://github.com/aws/language-server-runtimes/pull/145. This PR aims to tidy up the chat implementation, put shared code into functions and introduce testing around chat classes and functions
> Refine encryption

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Release new version of runtimes
> Release runtimes 0.2.8

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
> Release runtimes 0.2.9

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
> Upgrade runtimes version to 0.2.11

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Release runtimes 0.2.16
- Extend the protocol and server interface with Identity Management feature 
> Release runtimes 0.2.16

- package-lock.json
Vulnerability CVE-2024-45296
Update lockfile
> Update lockfile to fix dependency vulnerability

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Vulnerability found in dependency
Release new runtimes version
> Update runtimes version to 0.2.17

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
- Relax error codes in Identity Management protocol (#223).
- Minor changes in Identity Management protocol (#222).
> Update runtimes version to 0.2.20

- package-lock.json
- types/CHANGELOG.md
- types/package.json
> Update types version to 0.0.7

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Update runtimes version to 0.2.21
> Update runtimes version to 0.2.21

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
New features needs to be released
Bump version 0.2.22
> Update runtimes version to v0.2.22

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Update runtimes version to v0.2.24 with changes from #247.
> Update runtimes version to v0.2.24

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Bumping runtimes version to 0.2.25
> Update runtimes package version to 0.2.25

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Releasing runtimes version to 0.2.26
> Update runtimes version to 0.2.26

- .github/workflows/new_pr.yml
Added a notification in Slack whenever a PR is created.
> Added Slack notifier on PR creation

- chat-client-ui-types/src/uiContracts.ts
- types/chat.ts
Legal disclaimer in the chat client is too long.
Added a contract method for acknowledging a disclaimer with expanded legal information.
> Added disclaimer acknowledgement method to contract

- CONTRIBUTING.md
This is to test enforcing Conventional Commits spec in default branches at PR merge. Testing with test branches.
Testing https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/creating-rulesets-for-a-repository#enforce-conventional-commits
> [DO NOT MERGE IN MAIN] Test PR, ignore

- chat-client-ui-types/README.md
BREAKING CHANGE: update the version of package to next minor. This commit does not actually contain a breaking change, only to trigger a release.
> docs(chat-client-ui-types)!: updated README

- package-lock.json
- types/package.json
Version bump to avoid major version problems
> chore: bumped types version

- types/README.md
> feat(types): updated readme

- types/README.md
BREAKING CHANGE: update the version of package to next minor. This commit does not actually contain a breaking change, only to trigger a release.
> docs(types)!: update readme

- package-lock.json
- runtimes/package.json
We have unused dependency 
Remove zod from dependency list
> chore: remove unused zod dependency

- runtimes/runtimes/index.ts
- runtimes/tsconfig.json
Delete generated file from index.ts and add json schemas to /out dir.
> fix: add missing telemetry files

- runtimes/runtimes/standalone.ts
On exception, Standalone runtime exits abruptly and NodeJS may print whole application source code in stack trace.
Handle auth encryption token validation and process exceptions in Standalone runtime and print specific error message.
> fix(runtimes): catch unhandled encryption validation and process exceptions

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/util/standalone/proxyUtil.test.ts
- runtimes/runtimes/util/standalone/proxyUtil.ts
https://github.com/aws/language-server-runtimes/pull/335 does not emit metrics to client.
Emitting extra telemetry events for SDK proxy configuration utility.
> feat(runtimes): emit telemetry from SDK proxy configuration utility

- runtimes/protocol/chat.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/runtimes/chat/encryptedChat.ts
- runtimes/server-interface/chat.ts
- types/chat.ts
The PR adds an extension to chat with the ability to add support for inline chat through LSP. 
> feat: add extension for inline chat

- types/chat.ts
> feat: support additional chat message content to enable tool use

- types/chat.ts
> fix: buttons should be optional

- types/chat.ts
> fix: header icon should be optional

- types/chat.ts
> fix: missing messageId in fileClickParams

- types/chat.ts
> feat: support status in header

- runtimes/testing/TestFeatures.ts
Currently, `TestFeatures` does not have a clear API for mocking client params (`InitializeParams`), which requires verbose work arounds, e.g. `features.lsp.getClientInitializeParams.returns({} as InitializeParams)`. Furthermore, the `start` method does not trigger the handler set by `addInitializer`, so if it is necessary to mock the full LSP init flow, similar verbose workarounds are needed.
Add new methods to `TestFeatures` to make simulating (parts of) the LSP init flow clearer and easier, i.e.
- `setClientParams`
- `resetClientParams`
- `doSendInitializeRequest` (to trigger initializer handler)
- `doSendInitializedNotification` (to trigger initialized handler)
- `initialize` (similar to `start`, but also triggers the initializer handler and can help with configuring client params) …
> feat(runtimes): extend TestFeatures with API for simulating LSP init flow

- types/inlineCompletionWithReferences.ts
Implements the type changes needed for NEP edit suggestions in the language-server-runtimes repository.
> feat(types): add isEdit flag for next edit suggestion support

- types/chat.ts
- Missing some fields in `McpServerClickResult` interface for MCP
- Added required fields.
> fix: adding mcp interfaces

- types/inlineCompletionWithReferences.ts
> feat: adding additional fields to LogInlineCompletionSessionResultsParams

- types/chat.ts
Not clear what `modelId` is
Add docs
> docs: document modelId param

- types/inlineCompletionWithReferences.ts
Add new parameter shape for storing client IdeDiagnostic
> feat: add ideDiagnostic type

- runtimes/README.md
- runtimes/protocol/chat.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/server-interface/chat.ts
- types/chat.ts
This change sets up the protocols we will use to surface subscription details into the IDE plugins
> feat: subscription details protocols

- runtimes/runtimes/util/loggingUtil.ts
- types/chat.ts
We need some additional types to handle the show logs feature.
Added the types
> feat(types): enable show logs feature

- runtimes/protocol/lsp.ts
Need a feature flag for showLogs
Added a feature flag for showLogs
> feat(types): add a feature flag support for show logs

- runtimes/protocol/lsp.ts
> feat: add endpoint override option for easier dev setup

- runtimes/protocol/editCompletions.ts
- runtimes/protocol/inlineCompletionWithReferences.ts
- runtimes/protocol/lsp.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/lsp.ts
> feat(types): add predictionType as arg

- .release-please-manifest.json
- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/README.md
- runtimes/package.json
- runtimes/protocol/chat.ts
- runtimes/protocol/editCompletions.ts
- runtimes/protocol/identity-management.ts
- runtimes/protocol/inlineCompletionWithReferences.ts
- runtimes/protocol/lsp.ts
- runtimes/runtimes/agent.test.ts
- runtimes/runtimes/agent.ts
- runtimes/runtimes/auth/standalone/encryption.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/runtimes/lsp/router/initializeUtils.test.ts
- runtimes/runtimes/lsp/router/initializeUtils.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/util/loggingUtil.ts
- runtimes/runtimes/util/pathUtil.test.ts
- runtimes/runtimes/util/pathUtil.ts
- runtimes/server-interface/chat.ts
- runtimes/server-interface/identity-management.ts
- runtimes/server-interface/lsp.ts
- types/CHANGELOG.md
- types/auth.ts
- types/chat.ts
- types/package.json
feature/flareProtocolCodeGen is behind main
Merge main into the branch
> Update flareProtocolCodeGen to be in line with main

- types/chat.ts
This new field must be optional to not break other feature
update this to optional
> fix(types): metadata should be optional

- types/chat.ts
ListMcpServersResult needed actions for header buttons for mcp admin control.
- Added actions for ListMcpServersResult
> feat: added action to the list mcp servers result header for buttons

- runtimes/runtimes/util/telemetryLspServer.ts
VSCode Q chat experiences ~60-second delays when the telemetry endpoint `aws-language-servers.us-east-1.amazonaws.com` is not allowlisted in corporate networks.
Root Cause:
- Telemetry initialization runs synchronously during LSP server startup
- OTLPMetricExporter and OTLPLogExporter each attempt HTTP connections with timeouts
- Chat remains unresponsive until all telemetry timeouts complete
https://github.com/user-attachments/assets/88f89a4d-5321-4019-a3ec-8e6c87631d77
Make telemetry initialization to be non-blocking.
Changes:
- Wrap telemetry setup in setImmediate() callback
- LSP initialization returns immediately with `{ capabilities: {} }`
- Telemetry initializes asynchronously in background
Chat responds quickly even when telemetry URL is blocked …
> fix: initialize telemetry asynchronously without blocking
