- src/features/versioning.ts
- src/runtimes/initialize.test.ts
- src/runtimes/initialize.ts
- src/runtimes/runtime.ts
- src/runtimes/standalone.ts
- src/runtimes/webworker.ts
For webworker runtimes, the integrators will initialize the runtime with the server themselves. This makes the server version not meaningful in that case. We want to make it optional. Also this would match the serverInfo shape in [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) 
Make server version optional
> Make server version optional

- .github/dependabot.yml
- .github/workflows/runtimes-ci.yaml
- package.json
- src/features/auth/auth.test.ts
- src/features/auth/auth.ts
- src/features/auth/standalone/encryption.test.ts
- src/features/auth/standalone/encryption.ts
- src/features/index.ts
- src/features/logging.ts
- src/features/lsp/index.ts
- src/features/lsp/inline-completions/futureProtocol.ts
- src/features/lsp/inline-completions/protocolExtensions.ts
- src/features/lsp/textDocuments/textDocumentConnection.test.ts
- src/features/lsp/textDocuments/textDocumentConnection.ts
- src/features/telemetry/telemetry.ts
- src/features/versioning.test.ts
- src/features/versioning.ts
- src/features/workspace.ts
- src/runtimes/index.ts
- src/runtimes/initialize.test.ts
- src/runtimes/initialize.ts
- src/runtimes/runtime.ts
- src/runtimes/server.ts
- src/runtimes/standalone.ts
- src/runtimes/webworker.ts
- src/testing/TestFeatures.ts
- src/testing/index.ts
- tsconfig.json
Formatting rules between team-owned packages are misaligned.
[Added prettier rules](https://github.com/aws/language-server-runtimes/compare/formatting?expand=1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48-R56) matching https://github.com/aws/language-servers package and formatted all files.
No code changes were introduced, only cosmetic formatting changes.
> Add prettier rules and reformat source code

- src/features/lsp/index.ts
- src/runtimes/standalone.ts
- src/runtimes/webworker.ts
- src/testing/TestFeatures.ts
YAML JSON LSP Server needs to support formatting documents and send diagnostics when file opened.
- Added onDidFormatDocument and onDidOpenTextDocument support to LSP server interface.
- Added onDidOpenTextDocument, onHover, onDidFormatDocument to TestFeatures to add more tests in language-servers package
Tested in language-servers package, added tests there.
> Added onDidFormatDocument and onDidOpenTextDocument capabilities to DEXP LSP

- src/protocol/auth.ts
- src/protocol/lsp.ts
- src/runtimes/auth/auth.test.ts
[JSON-RPC protocol](https://www.jsonrpc.org/specification) allows passing parameters as an array (positinal) or as an object (by names). For example, 
```
rpc call with positional parameters:
--> {"jsonrpc": "2.0", "method": "subtract", "params": [42, 23], "id": 1}
<-- {"jsonrpc": "2.0", "result": 19, "id": 1}
rpc call with named parameters:
--> {"jsonrpc": "2.0", "method": "subtract", "params": {"subtrahend": 23, "minuend": 42}, "id": 3}
<-- {"jsonrpc": "2.0", "result": 19, "id": 3}
```
Previously, the CodeWhisperer LSP Server allowed `'aws/credentials/token/update'` JSON-RPC requests to pass parameters by name and positional. 
But [a recent refactoring in `aws/language-server-runtimes` changed the implementation](https://github.com/aws/language-server-runtimes/commit/3c74fee7af9c0cb2792c …
> Allow UpdateCredentials request params by-name and by-position

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/textDocuments/textDocumentConnection.test.ts
`hoverProvider` in server initialization response is always set to true. Hover is not handled by runtime directly, and instead should be set by injected capabilities servers at runtime time.
Remove hardcoded `hoverProvider` in `InitializeResult` response sent from runtime during connection handshake.
> Remove hardcoded hoverProvide set in server initialisation handler

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
Adds support for detecting and handling `workspace/didChangeWorkspaceFolders` notification. This will leveraged by CWSPR security scan server in the `aws/language-servers` repo to detect workspace change events and clear ir-relevant diagnostics.
> Add support for handling `workspace/didChangeWorkspaceFolders` notification

- package-lock.json
- runtimes/package.json
- runtimes/protocol/auth.ts
- runtimes/protocol/chat.ts
- runtimes/protocol/inlineCompletionWithReferences.ts
- runtimes/protocol/lsp.ts
- runtimes/server-interface/chat.ts
- types/README.md
- types/auth.ts
- types/chat.ts
- types/index.ts
- types/inlineCompletionWithReferences.ts
- types/lsp.ts
- types/package.json
All type besides chat-types are still in the runtimes package
- Move types to `types` package.
- Change re-export of  `vscode-languageserver-protocol` to `types` package in `runtimes` package
- Update dependencies
> Move types to types package

- types/package.json
"main" entry points to `out/` folder which is not included in the npm package structure when published, thus any programs that uses it (ex. vite) results in failed builds
Update main entry to default `index.js`
> Fix main entry for types package

- types/chat.ts
- types/lsp.ts
This PR makes 2 extensions to chat and quick action requests:
1. Adds optional partialResultToken to the request params to allow partial progress reporting
2. Adds optional cursorState field to the request params to allow clients to send cursor position or selection range details along with chat requests as additional context 
> Position in chat

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/README.md
- chat-client-ui-types/index.ts
- chat-client-ui-types/package.json
- chat-client-ui-types/tsconfig.json
- chat-client-ui-types/uiContracts.ts
- package.json
- runtimes/protocol/chat.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/chat.ts
- types/chat.ts
Creating a new package for defining chat client ui contracts between `chat client <-> ide extension` and `ide extension <-> chat server` These types will be consumed by chat clients defined in `aws/language-servers` 
> Create new subpackage for chat client ui types

- runtimes/CHANGELOG.md
- runtimes/package.json
Bump runtimes to version 0.2.4
> Bump runtimes to version 0.2.4

- chat-client-ui-types/tsconfig.json
Followup to https://github.com/aws/language-server-runtimes/pull/114, making tsconfig `rootDir` point to the `src` directory and not the root.
As per, https://www.typescriptlang.org/tsconfig/#tsBuildInfoFile, since we are now setting both outDir and rootDir, the `tsconfig.tsbuildinfo` file gets generated in the root instead of in the outDir. I set the `tsbuildinfo` field in tsconfig to make sure the file continues to be generated into the out directory
> Fix tsconfig rootdir for chat ui types

- chat-client-ui-types/src/uiContracts.ts
- runtimes/protocol/index.ts
- runtimes/protocol/telemetry.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/telemetry.ts
Telemetry endpoint in the protocol is not yet exposed
Enable endpoint in telemetry feature to enable clients sending telemetry to server
Also added additional UI chat contracts for copyCodeToClipboard and vote events 
This PR supports implementation in https://github.com/aws/language-servers/pull/249
> Telemetry endpoint in protocol

- types/chat.ts
The `recommendationContentSpan` field is optional but the fields inside it shouldn't be. This PR fixes it
> Make optional fields inside recommendationContentSpan mandatory

- types/chat.ts
ChatItemAction is missing optional `type` field (needed for auth follow-ups). 
FeedbackParams is missing optional `eventId` field
InfoLinkClick does not pass `messageId` but is required in it's params
Add missing fields and rearrange params for links interface structure
> Add missing field in ChatItemAction and adjust link params fields

- runtimes/protocol/chat.ts
- types/chat.ts
Move the hardcoded method names to the types package so they can be consumed 
> Extend chat types with method names

- chat-client-ui-types/package.json
Package imports couldn't be used without `/out` in path
Fix main entry in package.json
> Fix main entry typo

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
- package-lock.json
We want to use latest chat-client-ui-types version
Release new version
> Upgrade chat-client-ui-types version to 0.0.4

- chat-client-ui-types/src/uiContracts.ts
The `eventId` name (which was initially `triggerId`)  is confusing, this field will be used to send the information about what triggered the said action. For example send to prompt can be triggered by using a keyboard shortcut or using the context menu. This information will be useful for telemetry done by the server. 
The chat client will use the trigger type and send it to the server through the `telemetry` event, the server will then use this information for telemetry purposes as it will have the information about what kind of an interaction triggered a message/conversation
With this PR I am also removing the `tabidReceived` event since that information will be sent through `telemetry` operation
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Update chat types

- runtimes/protocol/chat.ts
- runtimes/protocol/lsp.ts
- runtimes/server-interface/lsp.ts
Following up on: https://github.com/aws/language-server-runtimes/pull/131, this PR takes only the chat quick action related changes from the other PR. Copying the description from the other PR:
We want to allow server implementations to register it's supported quick actions for Chat feature, to properly render chat at start time.
Extending default LSP `InitializeResult` objects with new backwards-compatible optional `awsServerCapabilities` attribute, scoped with `AWS`. This attribute is used to allow Server implementations to register customer features, defined by Language Servers runtimes protocol. First feature which is added is `chatQuickActionsProvider` for registering Quick Actions in Chat Client implementation (https://github.com/aws/language-servers/tree/main/chat-client).
By …
> Extend server handshake to register chat quick actions

- .github/workflows/runtimes-ci.yaml
Our GitHub actions use `npm install` which means that the resulting dependency tree can be different from what is in a `package-lock.json`.
Switched to the `npm ci` which is recommended for automated environments such as GitHub actions
https://docs.npmjs.com/cli/v10/commands/npm-ci
More info: [Why developers should use npm ci instead of npm install and its benefits?](https://support.deploybot.com/article/131-why-developers-should-use-npm-ci-instead-of-npm-install-and-its-benefits)
> Run npm ci instead of npm install in GitHub actions

- runtimes/protocol/chat.ts
- runtimes/runtimes/auth/standalone/encryption.ts
- runtimes/runtimes/chat/encryptedChat.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
- types/chat.ts
This PR introduces the encrypted chat class which ensures that quick action and chat prompt communication passing through the LSP connection is encrypted. The runtime handles the encryption and decryption and servers don't need to change anything
> Add encryption to chat

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
Release chat-client-ui-types 0.0.6
> Release/UI types 0.0.6

- runtimes/runtimes/chat/encryptedChat.ts
The library that handles to protocol need to be able to intercept `ResponseError` and returns corresponding exceptions. Since the handler results that are of `ResponseError` are encrypted, errors are not being thrown on Toolkit side.
Check if result is an instance of `ResponseError`
Verified that it works E2E in VS
> Return response error unencrypted

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
- runtimes/testing/TestFeatures.ts
The current type Lsp doesn't have the capability to respond to request `textDocument/semanticTokens/full` sent by client. 
This PR adds `semanticTokensProvider` to ServerCapabilities and register onSemanticTokens request handler. Then the runtime can use the handler to respond to the request `textDocument/semanticTokens/full`. This will enable the server to support SemanticTokens over LSP.
Tested the change on VSCode using the client `aws-lsp-partiql` in https://github.com/aws/language-servers.
> Add request handler for SemanticTokens

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Release v0.2.10
- https://github.com/aws/language-server-runtimes/pull/156
> Upgrade runtimes version to 0.2.10

- .github/workflows/publish-chat-types.yaml
- .github/workflows/publish-runtimes.yaml
- .github/workflows/publish-to-npm.yaml
- .github/workflows/publish-types.yaml
- .prettierignore
Publishing packages from Language Server Runtimes monorepo requires manual steps. 
Introducing workflows, which allow trigger publishing to npm from Github Action. Workflows will be triggered only when git tag with specific format is created per package we want to release:
* @aws/chat-client-ui-types: `chat-client-ui-types/v**`
* @aws/language-server-runtimes: `language-server-runtimes/v**`
* @aws/language-server-runtimes-types: `language-server-runtimes-types/v**`
Tags can be created using during release process using Github Releases webpage or manually using git CLI. This change also helps to align git tags formats we use.
Workflows will attempt to publish current version of packages, as set in their `package.json`, so proper release process still has to be followed to bump the version …
> Add Github Actions to automate publishing of packages to npm

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/util.ts
Servers couldn't run when multiple executeCommandProviders are given
Add conditional to InitializeResult merge logic when values are arrays
> Fix InitilizeResult merge logic

- runtimes/runtimes/chat/encryptedChat.ts
The progress completion handler in VS always start the token as 0 then increment after each request. The very first request will not have partial result because `0` is falsey. 
`partialResultToken` can be both numbers and strings, so it is reasonable to expect that `0` should work as a token. I think this handler can just include the partial result token and let the chat handler figure out what to do with it. Alternatively, we can just check whether it is undefined.
> Pass partial result token in chat request through to allow "0" to be used

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
- runtimes/testing/TestFeatures.ts
The current type Lsp doesn't have the capability to respond to request [textDocument/signatureHelp](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp) sent by client.
This PR adds signatureHelpProvider to ServerCapabilities and register onSignatureHelp request handler. Then the runtime can use the handler to respond to the request `textDocument/signatureHelp`. This will enable the server to support Signature Help over LSP.
Tested the change on VSCode using the client aws-lsp-partiql in https://github.com/aws/language-servers.
> Add onSignatureHelp Request Handler

- runtimes/CHANGELOG.md
- runtimes/package.json
Release of new package version: 0.2.12.
Release of new package version: 0.2.12.
> Upgrade runtimes version to 0.2.12

- package-lock.json
- types/package.json
This reverts commit 8e89e418896d21b9898f44962361f56c47c3cce3.
> Revert "Bump vscode-languageserver-textdocument from 1.0.11 to 1.0.12"

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
Runtimes don't support Window showMessage features.
Added support and bindings for 3 Window LSP features:
* `window/showMessage` notification ([spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage))
* `window/showMessageRequest` request ([spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest))
* `window/showDocument` request ([spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showDocument))
Adding bindings for these features allows Capability servers to request displaying UI flows in host clients natively. This allows to implement UX flows. whenever required by Capability business logic.
By submitting …
> Add window showMessage and showDocument LSP features to runtimes

- runtimes/CHANGELOG.md
- runtimes/package.json
Release Language Server Runtimes v0.2.13
- Add support for window/showDocument, window/showMessage and window/showMessageRequest LSP handler
> Upgrade runtimes version to 0.2.13

- .vscode/launch.json
- .vscode/tasks.json
- package.json
- types/package.json
No convenient way to run unit tests from VS Code to simplify test debugging.  types package had invalid package.json defined "main" script.
Fixed "main" script in types package to be out/index.js rather than just index.js.  Setup .vscode files and watch script similar to that in language-servers repo.  Now unit tests can be launched from VS Code.
> Enable unit test launch configurations for vscode

- .gitignore
- runtimes/protocol/lsp.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/router/lspServer.ts
- runtimes/server-interface/lsp.ts
Currently Server implementations don't have access to actual information about client host environment, which can be used to construct detailed metadata. Such data can be used in cases, when connected clients and host environments need to be unambiguously identified, for example to attach granular UserAgent header for HTTP calls or AWS SDK calls done by the server.
* Extended Language Server Protocol `InitializeParams` sent from LSP Client to the Runtime. This PR proposes to use unspecified standard `initializationOptions` field, and extend it with custom `aws` property, which isolates data for AWS Runtimes.
* Extended `InitializeParams` params passed from the Runtime to Server implementation, defined in `server-interface/lsp` interface.
* When Server's initialize method is called at …
> Accept Client metadata with LSP Initialization and inject standard UserAgent to Server implementations from the Runtime

- runtimes/CHANGELOG.md
- runtimes/package.json
Release Language Server Runtimes v0.2.14
> Update runtimes version to 0.2.14

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/util/sharedConfigFile.ts
The shared aws config isn't honored by JS SDK by default. 
If a customer has CA certificate bundle set in the config then it will be ignored by the JS SDK inside the LSP server which can lead to failures.
Setting `AWS_SDK_LOAD_CONFIG` environment variable in the standalone runtime so that the shared config is honored by default.
However, if we set this environment variable unconditionally the process will fail if there is no shared config on the file system. That's why we need to first check if the file exists. 
Also, SDK will check `AWS_CONFIG_FILE` environment variable that can override the default location. 
This solution inspired by https://github.com/aws/aws-toolkit-vscode/blob/2c8d6667ec45f747db25f456a524e50242ff454b/packages/core/src/auth/credentials/sharedCredentialsFile.ts#L44
By …
> Honor shared aws config file

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/workspace.ts
- runtimes/testing/TestFeatures.ts
Workspace feature does not expose function to get all open files in the IDE.
Added new method `getAllTextDocuments` which returns all documents managed by LSP server.
> Add getAllTextDocuments method to Workspace feature

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/router/lspServer.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- Added routing for `didChangeConfiguration` and `initialized` notifications so that all servers in a bundle will get the notifications instead of the last server that registered a handler 
> Add routing to initialized and didChangeConfiguration notifications

- runtimes/protocol/identity-management.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
Minor protocol changes needed for complementary PR with same name in language-servers repo.
1. Added AwsErrorCodes as base for other errors to support passing application (not JSON-RPC) error codes back to the destination to be able to filter errors more effectively.
2. Updated errors and added options parameter/type for listProfiles and updateProfiles
3. Fixed spelling of `updateProfilesRequestType` to `updateProfileRequestType` to be consistent with other updateProfile names
> Add listProfiles and updateProfile with ProfileService and store

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Release latest changes in Identity Management feature
> Update runtimes version to 0.2.19

- runtimes/protocol/identity-management.ts
1. Changes Profile to support multiple ProfileKinds as this is possible due to how customers may set up their shared config files.
2. Makes all settings and the settings properties of Profile and SsoSession optional to support removal of settings and sections from shared config files.
3. Adds ensureSsoAccountAccessScope option to UpdateProfile to allow opting out of automatic insertion of sso:account:access scope if not set
> Minor auth protocol changes

- runtimes/protocol/identity-management.ts
- runtimes/server-interface/identity-management.ts
This applies to identity-management only.
The prior definition of an error type per API is unnecessary as only an awsErrorCode is needed as additional data in all cases.
The rigid declaration of error codes as types was nice from a TypeScript declaration standpoint, but in practical terms of implementation, the error codes come from all levels/depths of code.  There is no practical way to guarantee the error codes will match the declared types at runtime as the types are erased.  This overcomplicated the code and required redeclaring all allowed error codes at every level of the code where an exception could be caught.  This is not practical for maintaining as additional error codes were added.
The changes here eliminate the type declarations for error codes as they're no longer needed. …
> Simplify errors and relax error codes allowed in identity-management

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
- package-lock.json
Releasing new version of `chat-client-ui-types`
> Update chat-client-ui-types version to 0.0.7

- runtimes/README.md
- runtimes/protocol/lsp.ts
`dataDirectory` requires more descripitive and consistent name.
- Renamed field in InitializeParams to a more descriptive and consistent name based on [feedback](https://github.com/aws/language-server-runtimes/pull/231#discussion_r1803524400). It's a breaking change, but the field is unused yet.
- Improved comments
> Renamed dataDirectory field to a more descriptive name

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/workspace.ts
With the addition of the notification protocol #231, the notification server implementation may require the following functions: create a directory, write to a file, append to a file.
Extended the workspace `fs` feature with a subset of Node.js file system methods. Currently, the workspace feature is implemented only in the standalone runtime.
Manually tested using a language servers' implementation.
> Extend FS feature with write operations

- .husky/pre-commit
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
- types/chat.ts
This PR introduces multiple changes:
1. Adds `workspace/applyEdit` functionality to the LSP interface. This will allow servers to make edits on the open text editors
2. Extends `insertToCursorPosition` params with two new fields: `cursorPosition` and `textDocument` (This will allow us to also get rid of some custom protocol changes done on the chat server https://github.com/aws/language-servers/pull/354/files#diff-fa30a0e5c15807fd776dbebef889da3272befc9c83e6ea90037cb74536e4647b also see the PR description: https://github.com/aws/language-servers/pull/354#issue-2378741043) 
3. Extends chat options with `defaultTabData` This can be used by servers to define the default tab data that is shown on the chat UI. Servers will be able to specify the chat message that should be shown by default as …
> Add `workspace/applyEdit` functionality to LSP interface & extend chat types  

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
- package-lock.json
Update chat-client-ui-types version to 0.0.8
> Update chat-client-ui-types version to 0.0.8

- runtimes/protocol/identity-management.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/identity-management.ts
This PR contains several updates for GetSsoToken, removes UpdateSsoTokenManagment and the Created & Invalidated events from SsoTokenChanged.  The latter two may be added back in the future if and when they are needed.
1. Added AwsErrorCodes and ordered alphabetically to help organize increasingly long list.
2. Moved clientName to GetSsoTokenParams from "source".
3. Add ssoRegistrationScopes to AWS Builder ID source.
4. Updated onGetSsoToken in standalone and webworker to encrypt accessToken before sending to client.
> Identity protocol updates and encrypt GetSsoToken.accessToken

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/runtime.ts
Servers might need to know value of platform in which they currently running. To avoid them computing this value in their business logic, we can send predictable value from the runtime itself.
Needed for https://github.com/aws/language-servers/pull/505
Pass new `platform` field in `Runtime` feature to every `Server`.
> Runtimes: pass runtime platform to Server implementation

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Release https://github.com/aws/language-server-runtimes/pull/244 to make it available for `language-servers`
Release `@aws/language-server-runtimes:v0.2.23` 
- Add `platform` value to `Runtime` feature injected in every Server (#244)
> Update runtimes to version v0.2.23

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/workspace.ts
Currently, in the standalone Workspace file system, there are some unreasonable default options passed to the Node.js fs functions, which can be confusing to the developers and produce unexpected results.
Changed the interface to align with the Node.js interface or documented it explicitly.
* The `remove` method is renamed to `rm`, and default options now align with the default Node.js behavior. Users will need to specify `force` and `recursive` options themselves.
* Both `readFile` and `readdir` methods pass options that aren't default, but their execution should be as expected by users, as these options change the return type. Added comments to additionally mark this.
* The `copy` method renamed to `copyFile` and `options.ensureDir` param to better describe its behavior along with docs …
> Align the FS interface with Node.js FS

- package.json
- runtimes/README.md
- runtimes/protocol/lsp.ts
- runtimes/protocol/notification.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/router/util.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
Notification protocol should be an optional capability for clients - it should support dynamic registration via client capabilities.
This change introduces `showNotification as a client capability. Client has to explicitly opt in to receive notifications.
In addition, the following changes were introduced:
- notification followup has to be sent per action (array was replaced with single action)
- server interface supports setting server name
- server name is checked for unique value in runtime
> Notification interface supports dynamic registration

- .vscode/launch.json
- runtimes/protocol/identity-management.ts
- runtimes/runtimes/standalone.ts
For the purposes of calling the Auth.update method in Flare with the results of GetSsoToken, destinations would need to decrypt the accessToken returned and reformat it for Auth.update.  While the ssoToken field is intended for extension and use of a token directly in a destination, there is value in avoiding decrypt/recrypt for destinations that need to call Auth.update.
This PR adds GetSsoTokenResult.updateCredentialsParams to provide the params a destination may provide to the Auth.update API without requiring any tranformation or work from the destination.  This is similar to the LSP ExecuteCommand pattern allowing servers to provide the appropriate arguments to a command so a client can just return what it received without need for additional detail or work.
> Add GetSsoTokenResult.updateCredentialsParams to avoid decrypt/recrtypt in destinations

- runtimes/runtimes/standalone.ts
UpdateCredentialsParams requires nested 'data' fields for encrypted credentials.  The standalone encryption needs to insert the extra data field nesting.
[decodeCredentialsRequestToken](https://github.com/aws/language-server-runtimes/blob/f1be234d5b336d76dc8b72517ca38a71b3818322/runtimes/runtimes/auth/auth.ts#L153) is used by the Auth update call to decrypt the token. It expects the encrypted `payload` (i.e. the return value from `encryptObjectWithKey`) to contain a `data` property. `request.data` was already dereferenced a few lines above and passed into `jwtDecrypt`.
[encryptObjectWithKey](https://github.com/aws/language-server-runtimes/blob/f1be234d5b336d76dc8b72517ca38a71b3818322/runtimes/runtimes/auth/standalone/encryption.ts#L93) is used in several places in the code base, including …
> UpdateCredentialsParams requires nested 'data' fields for encrypted credentials

- package-lock.json
- runtimes/CHANGELOG.md
- runtimes/package.json
Releasing runtimes 0.2.27
- Identity Management: Put SSO token inside the 'data' field for encrypted credentials as required by Auth
- Identity Management: Removed implicit sso:account:access scope in aws-lsp-identity. Removing unnecessary option from UpdateProfile
> Update runtimes version to 0.2.27

- runtimes/runtimes/encoding.test.ts
- runtimes/runtimes/encoding.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/router/lspServer.ts
- runtimes/runtimes/lsp/router/routerByServerName.test.ts
- runtimes/runtimes/lsp/router/routerByServerName.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
- runtimes/server-interface/notification.ts
Notification followup events from client need to be routed to the server of origin.
- Routing of notification followup events based on `serverName` + `id`, `id` fields is restored for followup events
- Encoding for web runtime supporting Unicode (should not be directly needed for routing functionality, but I wanted it supported from the very beginning for consistency with NodeJs version)
- Some refactoring in router by adding helper methods to make routing strategy used more explicit
- Unit tests
- Testing in test vscode client - result can be seen here: https://github.com/aws/language-servers/pull/622
> Routing for notifications

- runtimes/README.md
- runtimes/protocol/lsp.ts
- runtimes/runtimes/lsp/router/loggingServer.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/standalone.test.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/util/loggingUtil.test.ts
- runtimes/runtimes/util/loggingUtil.ts
- runtimes/runtimes/webworker.test.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/logging.ts
The PR includes the changes to support more logging levels as existing scenario has only method - which is log that outputs to lspConnection.console.info. The changes add support for error, warn, info, log, debug in the order of their severity. Log level can be decided by the client and when a runtime is executed, it requests Log level from client through LSP getConfiguration. 
Test cases for the changes have been added.
> Support more log levels in runtime logging feature

- .github/CODEOWNERS
There was no `.github/CODEOWNERS` file yet, but having this file is nice for confirming that the @aws/flare team owns this repository and should review PRs.
Added the file.
> Created CODEOWNERS file, indicating flare as owner of the repository

- .github/workflows/new_pr.yml
Currently, steps for dependabot PRs are failing
Do not push slack notifications for dependabot PRs:
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events
> Skip publish notification to slack for dependabot

- .github/workflows/new_pr.yml
Currently, steps for dependabot PRs are failing
Do not push slack notifications for dependabot PRs. (Fix of @volodkevych's PR, `github.actor` / `github.author` is invalid)
> Skip publishing Slack notification for Dependabot PRs

- .github/dependabot.yml
PRs created by Dependabot do not follow Conventional Commit spec by default.
Configure Dependabot to use Conventional Commit.
> chore: set dependabot to use conventional commit

- chat-client-ui-types/CHANGELOG.md
- chat-client-ui-types/package.json
Version should be bumped for new release of `@aws/chat-client-ui-types`, with the extension of UI contracts.
Bumped version to `0.0.9`
> chore(release): bump chat-client-ui-types version to 0.0.9

- .husky/pre-push
If conventional commits through git hooks were ignored (with `--no-verify`), then pushing to remote will still succeed. Let's add an additional layer to it.
Add commitlint command to the prepush script
> chore: add commit linting to prepush hook

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
Runtime details helps easily monitor and debug the LSP server startup, ensures customers are using the right version.
Added logging for server name, server version and capabilities during initialize request.
> feat(runtimes): log detail server info during initialization

- package-lock.json
- types/.npmignore
- types/package.json
The [published package on npm for `types`](https://www.npmjs.com/package/@aws/language-server-runtimes-types?activeTab=code) doesn't contain the `./out` folder however the `main` in `package.json` file refers to that.
This causes bundlers to fail since they're not able to find the `out/index.ts` file.
- Added individual `.npmignore` file to `types` folder to avoid `out` folder to be skipped because of parent folder `.gitignore` conflict
- Skipping all the files except package.json and the `out` folder
- Updated `pub` _(publish)_ script to use the root folder of `types` instead of `out` folder. The published package will contain the `out` folder.
- Updated version to `0.0.8`
> fix(types): npm publish (with out folder)

- types/.npmignore
- types/package.json
Even though the previous release fixed the `main` path targeting to the correct `./out` folder, it contains `.ts` files (not the `.d.ts`) which shouldn't be in the package. Also, some files like NOTICE, SECURITY etc. are missing.
Updated the `.npmignore` and fixed the copy files on `prepub`.
> fix(types): fixed publish package contents

- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/workspace.ts
Adding support for readFileSync method in workspace.fs feature of runtimes.
> feat: adding support for readFileSync method in workspace.fs

- runtimes/runtimes/lsp/textDocuments/textDocumentConnection.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/webworker.ts
- runtimes/server-interface/lsp.ts
Adding support for 4 native LSP methods:
- didSave: `textDocument/didSave`
- didRenameFiles `workspace/didRenameFiles`
- didCreateFiles `workspaceDidCreateFiles`
- didDeleteFiles: `workspaceDidDeleteFiles`
> Extend LSP interface

- runtimes/runtimes/lsp/router/lspServer.ts
- runtimes/runtimes/util/serverDataDirPath.ts
Prevent errors due to aws object being undefined and improve error handling in initialize method
Access aws object safely via with optional chaining and wrap the initialize method in a try/catch block logging error info
> fix: handling of aws object of initializationOptions and initialize error handling

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/server-interface/lsp.ts
We want to be able to listen to **textDocument/didSave** event for allowing LSP server to take an action upon file save. In order for the LSP server to be able to listen on the mentioned event, the initializeResult needs to return one more field `save` under capabilities.textDocumentSync. Property type of save field is described [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didSave) 
On a similar front, we also need to listen to **workspace/didCreateFiles**, **workspace/didDeleteFiles** and **workspace/didRenameFiles**. In order for LSP to be able to listen these events, we need to return one more capability from the InitializeResult response - which is workspace.fileOperations.didCreate/didRename/didDelete, which also …
> feat: add save option to initializeResult to allow LSP server to listen to save file events

- .github/workflows/new_pr.yml
Messages to Slack were being sent through the GitHub CI workflow, even for Draft PRs.
Filter to just run on non-draft PRs.
> ci: don't send slack messages for new prs in draft mode

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspServer.ts
Relevant PRs for the background : https://github.com/aws/language-server-runtimes/pull/307, https://github.com/aws/language-server-runtimes/pull/310 and https://github.com/aws/language-server-runtimes/pull/306
As part of the comment/ followup - we want to add observability related improvements including telemetry and try/catch blocks. 
As a followup to fixing the optional field 'aws' in the initialization options, this PR adds : 
1. Try/ catch block to the initialization of the router
2. Added a telemetry log event for observability 
> fix: adding try/catch to initialize lsp server, added telemetry log events 

- runtimes/runtimes/lsp/router/lspServer.test.ts
- runtimes/runtimes/lsp/router/lspServer.ts
Previously we added logging and emitted a metric when initialization failed due to missing fields in `initializationOptions`, it was however not verbose enough to be able to pinpoint the exact issue
Emit and log the exact full `initializationOptions` data
> chore: add initializationOption data to error log and metrics

- package-lock.json
- runtimes/package.json
- runtimes/protocol/lsp.ts
- runtimes/runtimes/operational-telemetry/README.md
- runtimes/runtimes/operational-telemetry/aws-metrics-exporter.test.ts
- runtimes/runtimes/operational-telemetry/aws-metrics-exporter.ts
- runtimes/runtimes/operational-telemetry/aws-spans-exporter.test.ts
- runtimes/runtimes/operational-telemetry/aws-spans-exporter.ts
- runtimes/runtimes/operational-telemetry/operational-telemetry-service.test.ts
- runtimes/runtimes/operational-telemetry/operational-telemetry-service.ts
- runtimes/runtimes/operational-telemetry/operational-telemetry.ts
- runtimes/runtimes/standalone.test.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/util/telemetryLspServer.ts
We need to respect customer decision and provide a way for them to opt-out of the operational telemetry.
- Extended the telemetry interface with a method to update telemetry opt out status, which determines if metrics are collected or not.
- Added another LSP server to the router that updates telemetry opt-out status upon initialization and when workspace configuration variables change.
- The OpenTelemetry SDK is shut down when a user turns off telemetry and started again when a user enables telemetry.
- Enabling or disabling telemetry does not require an IDE/extension restart.
> feat: add opt-out mechanism to operational telemetry

- .npmignore
- runtimes/package.json
`*.test.*` files are included in the `@aws/language-server-runtimes` npm package.
Deleted package.json `files` and updated .npmignore to exclude test files. Npm will not use .npmignore if `files` are present. Impact:
* Removed 54 unnecessary files
* Reduced package size by 28.4kB
* Reduced unpacked size by 216.8kB
Added missing files: NOTICE, SECRUITY.md and CHANGELOG.md.
Tested by installing the new runtimes tarball package in `aws-lsp-codewhisperer` and running `npm run test`. Also tested manually by comparing outputs using `npm publish --dry-run` in  the runtimes `pub` script.
> chore: remove test files from package and include missing .md files

- README.md
There is no explanation on the relation between [servers](https://github.com/aws/language-servers) and runtimes, which causes confusion for developers new to the repo.
Add a brief explanation in the README
> docs: add explanation on differences with servers

- runtimes/protocol/configuration.ts
- runtimes/protocol/index.ts
- runtimes/protocol/lsp.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/router/lspServer.test.ts
- runtimes/runtimes/lsp/router/lspServer.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/lsp.ts
Some E2E features require support for clients to receive synchronous confirmation of LSP configuration updates, handled by Language Servers. Currently, standard LSP only supports server pull and LSP Notifications models.
1. Add new `UpdateConfiguration` LSP RequestType as protocol extension. Implemented support of broadcasting `UpdateConfiguration` request to all registered Servers in LSPRouter: aggregating responses and returning error based on handler responses.
2. Extended LSP feature passed to Server implementation with new `lsp.workspace.onUpdateConfiguration` handler registration point. Every Server implementation may subscribe to this request and implement synchronous configuration handling logic.
```
import { standalone } from '../runtimes'
import { Server } from …
```
> feat(runtimes): add UpdateConfiguration protocol and Server handlers

- runtimes/protocol/chat.ts
- runtimes/runtimes/auth/auth.test.ts
- runtimes/runtimes/auth/auth.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/server-interface/auth.ts
- runtimes/server-interface/chat.ts
- types/auth.ts
- types/chat.ts
There is no way to request chat UI to open a new tab from server. This will be needed to restore chat state after profile switch.
Given connection type becomes required now for region detection, we should move it to `aws/credentails/token/update` request - it simplifies the flow and less error-prone.
- extended chat protocol with `'aws/chat/openTab'`
- extended `UpdateCredentialsParams` in `'aws/credentials/token/update'` with `startUrl`
- moved the logic to define connection type to runtimes
> Update protocol for regions use cases

- runtimes/runtimes/util/standalone/proxyUtil.test.ts
The test defined [here](https://github.com/aws/language-server-runtimes/blob/a82a70810592909e1d82c74406124de847f1af0b/runtimes/runtimes/util/standalone/proxyUtil.test.ts#L198) for testing certificate fails sometime with timeout exceed error. The test case uses generateCert function, which uses 'node-forge' library to generate certificates which can be resource intensive at times. On my local as well, I saw the test case running in 1468ms for one of the instance. There are other test cases in the file which are using generateCert function, so there is a possibility of getting the same error for those test cases as well. 
Mocha has a default timeout of 2000ms per test case. Mocha provides us the capability to override this timeout value or even disable timeout when we provide 0 value to the …
> fix: fix the flaky test timeout error

- runtimes/README.md
- runtimes/protocol/identity-management.ts
This PR implements the required types to add device code auth support to the Identity Server. Currently, only PKCE auth flow is supported.
- E_CANCELLED error to indicate the auth flow was cancelled
- `GetSsoTokenProgress` and related types, to indicate to the client whether an authentication is in progress
- `AuthorizationFlowKind` and related types, to indicate what auth flow to use when requesting an SSO token
> feat(types): types for device code support

- runtimes/runtimes/util/standalone/proxyUtil.test.ts
- runtimes/runtimes/util/standalone/proxyUtil.ts
When reading certificates from OS fails, SDK client proxy agent is configured with no SSL certificates at all, which cause requests to fail.
Keep NodeJS's built-in certificates in HTTP agent configuration, as they are good to work with AWS SDK by default.
> fix(runtimes): maintain nodejs built-in certificates for SDK proxy configuration

- chat-client-ui-types/src/uiContracts.ts
- types/chat.ts
- There is no mechanism to return error from `chat-client` to the calling party
Extended the protocol to support errors as part of  response over `postMessage`.
> feat: improvements for "openTab" request flow

- runtimes/testing/TestFeatures.ts
doUpdateConfiguration helper is needed for adding tests for new UpdateConfiguration API in language servers (e.g. https://github.com/aws/language-servers/pull/822)
Added new helper to TestFeatures
> fix(runtimes): add doUpdateConfiguration to TestFeatures

- runtimes/protocol/lsp.ts
For language server `aws-lsp-codewhisperer` in particular, we need a way for clients to be able to signal that they support Q developer profiles at initialization.
Extend the `awsClientCapabilities` entry of `AWSInitializationOptions` with `[key: string]: any`. This enables clients to signal support for server-specific capabilities in a generic way.
Testing: build and installed the change into a local copy of the language servers repository to verify that the server can now parse for any client capabilities.
> feat(runtimes): extend awsClientCapabilities generically to signal server-specific capabilities

- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- runtimes/runtimes/util/lspCacheUtil.test.ts
- runtimes/runtimes/util/lspCacheUtil.ts
- runtimes/server-interface/lsp.ts
It is becoming more frequent that the `initializeParams` sent by the client have to be referenced in different parts of a server _after_ initialization. We need a more scalable way to retrieve these parameters to avoid duplication or having to couple components with the initialization code.
The `LspRouter` already caches the client `initializeParams`, so to make these available we can extend the `lsp` feature with a method/property `getClientInitializeParams`, which retrieves the cached client params in the `LspRouter`. Example usage:
```ts
// somewhere in language-servers/servers/aws-lsp-*
const params: InitializeParams = lsp.getClientInitializeParams()
```
Testing: Created a reusable handler for this purpose with unit test. Also packed and installed in a local copy of `language-servers` …
> feat(runtimes): cache and expose initializeParams as a feature

- .github/workflows/new_pr.yml
The Slack notification workflow fails on PRs from forked repositories. These failures are false positives and create unnecessary noise in our CI pipeline.
Reason is that GitHub Secrets are not passed to the runner when a workflow is triggered from a forked repository, because of security reasons.
Disabling slack notification workflow for PRs coming from forks. We could think of some better solution that will work with forks in the future.
> chore: disable slack notifications for PRs from forks

- types/inlineCompletionWithReferences.ts
We need to support import adder feature for inline completions through language server
add import to `InlineCompletionItemWithReferences` interface
> feat(types): add imports to InlineCompletionItemWithReferences type

- types/chat.ts
We want to implement context transparency feature which allows for a header to be accepted. This header can be used to provide context of the files used to the user. For this purpose we add a new ChatItemContent type which accepts few fields. 
> feat: add chat message content to support context transparency

- runtimes/protocol/chat.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/runtimes/chat/encryptedChat.ts
- runtimes/server-interface/chat.ts
- types/chat.ts
The PR adds requestId to the response of inline chat, as it's needed by client for emitting telemetry. Similar to how these parameters are passed from InlineCompletion response.
> fix: add requestId to InlineChat response

- runtimes/runtimes/agent.test.ts
- runtimes/runtimes/agent.ts
- runtimes/server-interface/agent.ts
The Bedrock JSON Schema allows any extension keyword to be defined, so we have to support a string indexer field.
When providing mixed required and non-required properties in JSON objects, they were not inferred properly.
> fix: support JSON Schema extension keywords and properly infer required fields

- chat-client-ui-types/src/uiContracts.ts
- types/chat.ts
We don't have a way to integrate the current welcome screen in Q through flare
Extending to protocol so we can integrate the welcome screen UI in flare
> feat: extend tabdata interface to include support for welcome screen

- types/chat.ts
In order to implement `@workspace` context in chat, the server needs to understand context sent from Mynah UI. 
Following the example in [vscode toolkits](https://github.com/aws/aws-toolkit-vscode/blob/a96a73e7ae55d7149684141b066f1b8b8413322f/packages/core/src/codewhispererChat/controllers/chat/model.ts#L107).
The context is added to `ChatParams`. I am not sure why context can be a string. Just added to be compatible with the Toolkits interface.
> feat(types): add context to ChatParams

- runtimes/server-interface/workspace.ts
This Dirent interface is difficult to work with for two reasons:
- it uses deprecated and confusing path field ([https://github.com/nodejs/node/issues/51955#issuecomment-1977131319 ](https://github.com/nodejs/node/issues/51955#issuecomment-1977131319)). To summarize, path is the same as parentPath on node 20, but not node 18. this is not clear in the name. 
- does not provide a way to check for links, which are returned by fs.readdir.
- update interface to avoid deprecated field, and expose the predicate for checking links. 
> fix: update Dirent interface. 

- runtimes/runtimes/standalone.ts
- runtimes/server-interface/workspace.ts
We need to pass in mode to fs.writeFile from a recent app sec finding
add optional mode as param for writeFile
> feat(types): add mode to fs writeFile

- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/workspace.ts
The home directory is currently fetched via https://github.com/aws/language-servers/blob/ecd755576df2d2e3ca4591cf44b605d7b72b0bc3/core/aws-lsp-core/src/util/path.ts#L96 for components that require it, but this is not available on web. 
Rather than adding web-safe checks around this, we should inject this into the runtime via the `Workspace` interface. 
Injecting this behavior will also make it easier to test certain scenarios as we can directly manipulate the home directory without mocking. 
- Add `workspace.fs.getUserHomeDir` that resolves to `os.homedir()` on standalone processes. 
- Default to an empty string in web browsers where there is no concept of home directories. 
- For fetching server directory on web, attempt to use `initializationOptions.clientDataFolder` and fallback to …
> feat: inject home directory into runtimes. 

- runtimes/runtimes/standalone.ts
Since truncated logging from bundling minimization modifies and makes class/function names unrecognizable, we remove class name logging from runtimes, instead and we log directly hardoded class names from language-servers (see https://github.com/aws/language-servers/pull/909)
> fix(log): remove logging class names

- runtimes/protocol/lsp.ts
Local project context needs to be configurable within different IDEs with rules for files to exclude from indexing, as well as supported languages.
Add a `ContextConfiguration` parameter to the `AWSInitializationOptions` interface to be provided during initialization that will determine how local project context will index the workspace. Additional user defined configuration will be available through the `workspace/configuration` call.
> Add initialization configuration options for file indexing

- runtimes/protocol/lsp.ts
The global context configuration param is incorrect.
Update the global context configuration param to be `ContextConfiguration`.
> Fix global context configuration param type

- chat-client-ui-types/src/uiContracts.ts
we need a way to dismiss the pair programming card used in agentic chat
when the "X" is pressed on the pair programming card it will send a pairProgrammingAcknowledged event to VSCode
> chore(chat-client-ui-types): add pair programming card acknowledgement command

- chat-client-ui-types/src/uiContracts.ts
Instead of tying the message send from chat-client -> editors to pair programming, lets make it generic and send a message id and let clients handle this on their side
> fix: change pair programming acknowledged to chat prompt option acknowledged

- types/chat.ts
In order to answer a prompt that requires multiple reasoning steps and tool usages, we need to be able to reply with more than one message.
In order to maintain backwards compatibility and indicate the relationship between the messages, an array of `additionalMessages` is added to `ChatResult` to contain the supporting materials.
There's 2 ways to use it:
1. Use the primary message only for the final result, and use `additionalMessages` for all intermediate messages. This would keep the primary message empty until the prompt finally resolves. This means that clients that don't know about this property, will not render anything until completed.
2. Put the most recent message in the primary message, and move the previous messages into `additionalMessages`. Then, as more information comes …
> feat: add additional messages in support of the final response

- chat-client-ui-types/src/uiContracts.ts
for agentic chat we need a way for the chat client to tell VSCode that we should stop the chat request stream
add it
The implementation of how this event would be used is:
- send a notification from chat-client to VSCode
- cancel the token for the active chat request stream
- replicate the equivalent of [this code](https://github.com/aws/aws-toolkit-vscode/blob/feature/agentic-chat/packages/core/src/codewhispererChat/controllers/chat/controller.ts#L415) in flare
> feat: add stopResponse ui event

- runtimes/runtimes/base-runtime.ts
linked up to incorrect request type. [https://github.com/aws/language-server-runtimes/commit/32b3bb9cca7bf09d412e87cc9e062ac99d847bd2#diff-3b7ccc3150a65fa49ff[…]744a5a58a75768fde5de0R168](https://github.com/aws/language-server-runtimes/commit/32b3bb9cca7bf09d412e87cc9e062ac99d847bd2#diff-3b7ccc3150a65fa49ffbc0f6d5f2beb4a487251387f744a5a58a75768fde5de0R168)
- use the proper request type. 
> fix: route correct request type to button click

- chat-client-ui-types/src/uiContracts.ts
Currently we need a way to inject features such as contextCommands into our chat client. This PR is needed to copy over the types that the vscode team are also using
> feat: extending ui contract with dynamic feature config types

- types/workspace.ts
We need a way to tell clients what the original file contains at the time of generating a diff.
Add optional field `originalFileContent` which may be different from the contents of the file at the current point in time.
> feat: support file snapshot for diffs

- chat-client-ui-types/src/uiContracts.ts
To support `aws.amazonq.ExplainIssue` in security scan for VSCode we need to have a way to send a generic message to the chat client and automatically submit that message
Add an autoSubmit, prompt param to SendToPromptParams. This option will be disabled by default. Only when the IDE explicitily indicates that the user intends for this to automatically send will it auto submit
> feat: add autoSubmit param to SendToPromptParams

- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/util/pathUtil.test.ts
- runtimes/runtimes/util/pathUtil.ts
path is imported to join paths on web. This was assumed to be safe since `path` is polyfilled with `path-browserify` in the webpack config. However, this polyfill requires consumers to add this dependency, which can be undesirable. 
- write our own simplified join for unix paths that can be used in the browser case. 
- remove path import. 
> fix: avoid path import on web.

- runtimes/protocol/lsp.ts
We need an identifier to uniquely and consistently identify an IDE workspace.
Extension would pass such an identifier to AWSInitializationOptions
> feat: add workspaceIdentifier to AWSInitializationOptions

- runtimes/runtimes/agent.test.ts
- runtimes/runtimes/agent.ts
- runtimes/server-interface/agent.ts
To support MCP server removal or updates, the Agent needs the ability to dynamically remove tools.
Add a removeTool interface in the Agent to enable tool removal.
> feat: support remove tool in Agent

- runtimes/runtimes/util/standalone/experimentalProxyUtil.test.ts
- runtimes/runtimes/util/standalone/experimentalProxyUtil.ts
The tests are failing because one of the `tls.rootCertificates` expired yesterday. The proxy manager correctly filters out expired certificates, but in tests we compare it against all certificates.
Added a function in tests to filter expired certificates.
> fix: filter expired certificates in tets

- package-lock.json
- runtimes/package.json
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/lsp/router/initializeUtils.test.ts
- runtimes/runtimes/lsp/router/initializeUtils.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/lsp/router/lspServer.test.ts
- runtimes/runtimes/lsp/router/lspServer.ts
- runtimes/runtimes/standalone.test.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/workspace.ts
Currently in a lot of downstream servers, the `workspace.getWorkspaceFolder` method is used for path resolution. This only relied on the `initializeParams.workspaceFolder` value which did not take into account workspace folder changes(did not listen to `didChangeWorkspaceFolders`) that could have happened during the session.
In addition with VS client as mentioned in https://github.com/aws/language-servers/pull/1210, the workspaceFolder value is not set(more details in that PR) however it does specify that information via `rootUri` and `rootPath`. The utility class from that PR has now been moved centrally to this repo.
A new `getAllWorkspaceFolders()` call has been added as a common utility that servers downstream can use as single source of truth to get latest information of …
> feat: support using rootUri for workspaceFolders and handle workspaceChangeEvent

- runtimes/runtimes/operational-telemetry/operational-telemetry-service.test.ts
We currently need to update test values whenever we update OpenTelemetry SDK dependencies.
Assigned constant values to test requests to make them independent of SDK versions.
> fix: make test independent of sdk version

- types/chat.ts
- Adding missing `summary` field to `ChatMessage` for MCP chat summary UX.
> fix: adding summary to ChatMessage

- types/chat.ts
The MCPServer click item can be 
```
{
"id": "save-mcp",
"title": "Save configuration",
"optionsValues": {
"scope": "",
"name": "p",
"transport": "yes",
"command": "npx",
"args": [{ "arg_key": "@playwright/mcp@latest" }],
"env_variables": [{ "env_var_name": "", "env_var_value": "" }],
"timeout": "60"
}
}
```
that current protocol cannot parse. It happens when you add a MCP server with args and env variables. 
Support JSON data as mentioned above. 
> fix: support nested mcp server click param option values

- runtimes/runtimes/auth/auth.test.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
PR #509 added a check to validate whether the client supports workspaceFolders before handling the didChangeWorkspaceFolders event. This fails for VS as VS does not send the workspaceFolder value
Check has been removed as it is now assumed that whenever this is invoked clients intentionally want to send this event.
This also unblocks VS which sends the workspaceFolder information with rootUri of the initializeParams
> fix: remove the supports workspace check for didChangeWorkspaceFolder event

- types/chat.ts
Reverts aws/language-server-runtimes#523
In the language server, we are parsing the string to get env var and arg key
See 
```
// Handle the case where argsValue might be a direct array or another type
try {
// Try to safely access and process the value
const argsArray = Array.isArray(argsValue) ? argsValue : []
args = argsArray
.map((item: any) => {
return typeof item === 'object' && item !== null && 'arg_key' in item ? String(item.arg_key) : ''
})
.filter(Boolean)
} catch (e) {
this.#features.logging.warn(`Failed to process args: ${e}`)
}
// Process env_variables to Record<string, string>
let env: Record<string, string> = {}
const envValue = params.optionsValues.env_variables
// Handle the case where envValue might be a direct array or another type
try {
// Try to safely access and …
```
> Revert "fix: support nested mcp server click param option values"

- types/inlineCompletionWithReferences.ts
we need to populate new fields via user decision for NEP
adding additional fields to LogInlineCompletionSessionResultsParams for NEP telemetry events
> feat: adding additional fields to LogInlineCompletionSessionResultsParams

- runtimes/runtimes/operational-telemetry/operational-telemetry-service.ts
- runtimes/runtimes/util/telemetryLspServer.ts
We need to begin sending operational telemetry for users of our runtime. Telemetry sharing is disabled by default when no configuration is specified.
* Initialized OperationalTelemetryService during LSP initialization
* Increased interval for exporting logs to backend
* Added telemetry endpoint
Manually tested with "CodeWhisperer Agentic Server Token" extension in [language-servers](https://github.com/aws/language-servers/blob/main/.vscode/launch.json). Used `TELEMETRY_GATEWAY_ENDPOINT` to direct telemetry to a non-prod endpoint. Added 'telemetryOptOut' in `initializationOptions` in [activation.ts](https://github.com/aws/language-servers/blob/main/client/vscode/src/activation.ts) file.
Tested scenarios:
* `telemetryOptOut: true` - OpenTelemetry SDK is not initialized and telemetry is not …
> feat: enable operational telemetry

- types/chat.ts
ChatOptionsUpdate notification needs to be able to set options for a specific tab
Add tabId to `ChatOptionsUpdateParams`
> feat: add tabId to ChatOptionsUpdateParams

- types/inlineCompletionWithReferences.ts
adding isInlineEdit to LogInlineCompletionSessionResultsParams
adding isInlineEdit to LogInlineCompletionSessionResultsParams
> feat: adding isInlineEdit to LogInlineCompletionSessionResultsParams

- runtimes/runtimes/chat/encryptedChat.ts
- runtimes/runtimes/encoding.ts
- runtimes/runtimes/lsp/router/initializeUtils.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
- runtimes/runtimes/standalone.test.ts
- runtimes/runtimes/util/serverDataDirPath.ts
- runtimes/runtimes/util/sharedConfigFile.ts
- runtimes/runtimes/util/standalone/certificatesReaders.ts
- runtimes/script/generate-types.ts
Some Mac builds were failing due to TypeScript syntax errors including:
- Missing `override` keywords on method overrides
- Inconsistent import statement formats (default vs namespace imports)
- Missing return statements in functions
- Type casting issues
Additionally, there was a flaky test `should use os.tmpdir() path when on non-Darwin systems` that was failing due to incorrect stubbing approach and cross-platform testing assumptions.
1. **Fixed TypeScript syntax errors** by applying changes from commit e77edadcdd5e28ea79fce41696bdc00c25316b50:
- Added `override` keywords to method overrides in `encryptedChat.ts`
- Changed default imports to namespace imports (`import * as path from 'path'`) in 6 files
- Added explicit type casting `(char as string)` in `encoding.ts`
- Added missing …
> fix: syntax errors on some Mac builds and flaky Darwin test

- package-lock.json
- runtimes/package.json
- runtimes/runtimes/util/standalone/experimentalProxyUtil.test.ts
- runtimes/runtimes/util/standalone/experimentalProxyUtil.ts
Standalone runtime is only able to use proxies when the user explicitly set the HTTP(S)_PROXY environment variables. 
Users on corporate networks use Transparent proxies configured on Network level. Retrieving the OS certificates trust store is not enough. As a result of this, customers requests to Q Agentic Chat fail as they do not pass through their corporate proxy.
We embedded automatic system‑proxy discovery into the standalone language‑server by adding the lightweight [os‑proxy-config](https://www.npmjs.com/package/os-proxy-config?activeTab=readme) package and a tiny synchronous shim that runs it in a child Node process when no HTTP(S)_PROXY env‑vars are set. The shim was used to keep the method synchronous, so that the async changes would not ripple through every SDK-client factory …
> feat(runtimes): add auto-discovery for OS proxy settings

- runtimes/runtimes/util/standalone/experimentalProxyUtil.ts
The current implementation of `getSystemProxySync()` fails to correctly detect system 
proxy settings on Windows, resulting in an empty object being returned even when a 
proxy is configured. This occurs due to inconsistencies in how the Node.js sub-process 
is executed across different platforms.
Use `execFileSync` with the '-e' flag to execute the script, matching the command-line approach.
Ran this command in my windows terminal:
```
PS C:\Users\tsmithsz> & "C:\Program Files\nodejs\node.exe" `
>>   -e "import('os-proxy-config').then(m=>m.getSystemProxy()).then(console.log).catch(console.error)"
{
proxyUrl: 'http://localhost:8888/',
noProxy: [ 'localhost', '127.0.0.1', '::1' ]
}
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix: align proxy detection with Node.js CLI behavior in Windows

- runtimes/protocol/inlineCompletionWithReferences.ts
- runtimes/protocol/inlineCompletions.ts
There is a circular dependency between`runtimes/protocol/inlineCompletionWithReference.ts` and `runtimes/protocol/lsp.ts`. And another similar circular dependency between`runtimes/protocol/inlineCompletions.ts` and `runtimes/protocol/lsp.ts`.
It happens as lsp.ts exports * from inlineCompletionWithReference.ts, but inlineCompletionWithReference imports several class from lsp.ts. Same thing happens for inlineCompletions.ts.
The classes imported from lsp.ts are essentially from vscode-languaugeserver-protocol. To avoid circular dependency, have inlineCompletionWithReference.ts and inlineCompletions.ts directly import these classes from vscode-languageserver-protocol.
> fix(runtimes): fix protocol/lsp circular dependency

- runtimes/runtimes/agent.test.ts
- runtimes/runtimes/agent.ts
- When model passes incorrect type for the toolUse input, the error msg is not clear enough to allow auto correction
```
"toolResults": [
{
"toolUseId": "tooluse_f3iftfAAQ8uhRCHp1oJQCg",
"status": "error",
"content": [
{
"json": {
"error": "Input for tool fsReplace is invalid"
}
}
]
}
]
```
- improve tool input validation logic to return specific error message
> fix: improve tool input validation logic to return specific error message

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
Visual Studio was sending duplicate workspace folder URIs in workspace change events, which caused duplicate rules to appear when listing rules.
Added deduplication filter to check existing workspace folder URIs before adding new ones, preventing duplicates from being stored in the workspaceFolders array.
> fix: remove duplicate uri of workspace paths sent by VS

- runtimes/runtimes/lsp/router/lspRouter.test.ts
- runtimes/runtimes/lsp/router/lspRouter.ts
Previous solution only avoids exact the same URL but sometimes the URL is the same but some with '/' in the end that causes duplicates in rules.
Remove the forward slash and then compare the values. 
> fix: avoid duplicate url with forward slash in the end

- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- Server could not receive onDidSaveTextDocument event from VSCode
- Connect the lspServer to the documentObserver.
- Linked lsp-runtime and lsp, manually tested. Now WorkspaceContextServer can receive the didSave event:
```2025-06-27 14:37:03.013 [info] [2025-06-27T21:37:03.013Z] Received didSave event for /Volumes/workplace/<*redacted*>```
> fix: onDidSaveTextDocument routing

- package-lock.json
- runtimes/package.json
- runtimes/runtimes/util/standalone/experimentalProxyUtil.ts
- runtimes/runtimes/util/standalone/getProxySettings/getMacProxySettings.test.ts
- runtimes/runtimes/util/standalone/getProxySettings/getMacProxySettings.ts
- runtimes/runtimes/util/standalone/getProxySettings/getWindowsProxySettings.test.ts
- runtimes/runtimes/util/standalone/getProxySettings/getWindowsProxySettings.ts
- runtimes/runtimes/util/standalone/getProxySettings/parseScutil.test.ts
- runtimes/runtimes/util/standalone/getProxySettings/parseScutil.ts
Related PR:
- https://github.com/aws/language-server-runtimes/pull/553
We originally bolted on an exec-time shim that `require.resolve’d` [os-proxy-config](https://www.npmjs.com/package/os-proxy-config) and ran it in a child-process so we could keep `ProxyConfigManager.getSystemProxySync()` fully synchronous. This avoided a ripple-effect async refactor through every SDK-initialisation call-chain and let us ship quickly, but it also meant the code was never picked up by Webpack, so the proxy lookup silently no-oped inside the bundled LSP.
- Vendored the tiny os-proxy-config implementation directly  (`getMacProxySettings.ts`, `getWindowsProxySettings.ts`) and removed the child-process shim.
- Reference Code: [os-proxy-config](https://github.com/httptoolkit/os-proxy-config), …
> fix: refactor auto-discovery for OS proxy settings

- types/chat.ts
handle keyboard shortcut for execute shell commands
[toolkit PR](https://github.com/aws/aws-toolkit-vscode/pull/7655)
[language-server PR](https://github.com/aws/language-servers/pull/1885)
> feat(types): add type to executeShellCommandShortCut param

- runtimes/runtimes/standalone.ts
when server is exiting unexpectedly,
there is no guarantee that console.log will propagate back to LSP client
log directly to stderr
> fix: in standalone, log uncaughtException errors directly to stderr

- types/chat.ts
Replace constant method type for executeShellCommandShortcut
> feat(types): add method type for execute shell command shortcut

- runtimes/protocol/identity-management.ts
- runtimes/runtimes/auth/standalone/encryption.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/identity-management.ts
- types/auth.ts
While the identity management LSP can manage SSO tokens, it lacks the types and handlers needed to manage IAM credentials. This forces IDE extensions to manage IAM credentials themselves, which adds complexity to them.
This is part of #572 
To facilitate IAM credential management, this PR adds the getIamCredential handler to give IDE extensions a way to retrieve a profile's IAM credentials according to the profile's stored configurations. Each IAM-related configuration is associated with at least one of the new profile types: IamCredentialsProfile, IamSourceProfileProfile, IamCredentialSourceProfile, or IamCredentialProcessProfile. These profiles follow the specification from the [AWS CLI](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html) and will be used in future …
> feat(runtimes): add handlers for IAM and STS credentials management

- runtimes/README.md
- runtimes/protocol/chat.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/chat/baseChat.ts
- runtimes/server-interface/chat.ts
- types/chat.ts
This reverts commit 9cec0d7a3ce9001a1ef7f0b3c72a624a1c8919b3 (#623).
#620 was reverted because supporting changes weren't added to language-servers repo in order to prevent a compilation failure. These protocol changes are being developed in a feature branch, so it will be a while before they are integrated into the main repo.
Do not merge this commit until after https://github.com/aws/language-servers/pull/1925 has been merged into the language servers repo. This will prevent the compilation failures by stubbing (omitting) the functions being added to `Chat`
> revert: revert: subscription details protocols #620 (#623)"

- types/chat.ts
This change updates part of the subscription protocol based on recent developments and requests.
SubscriptionDetailsParams is being updated so that
- we can tell if the subscription has overages enabled
- when the subscription period ends
> chore: update SubscriptionDetailsParams fields

- runtimes/runtimes/lsp/router/initializeUtils.test.ts
- runtimes/runtimes/lsp/router/initializeUtils.ts
- runtimes/runtimes/util/pathUtil.test.ts
- runtimes/runtimes/util/pathUtil.ts
`getWorkspaceFoldersFromInit` function is using the node-only `path` module. It is imported by `base-runtime.ts` which in turn is used in `webworker`. This causes consumers to require using polyfills, which is not always an option as it is an unmaintained package.
https://github.com/aws/language-server-runtimes/issues/588
Implement a custom platform-agnostic implementation of the `path.basename` function, similar of the `joinUnixPaths` made to replace `path.join`. This should match the behaviour of the original function and thus not break the functionality of `getWorkspaceFoldersFromInit`
> fix: replace path.basename with custom browser-safe implementation

- runtimes/runtimes/agent.test.ts
- runtimes/runtimes/agent.ts
- Sometimes LLM still cannot auto correct issues with diffs array type mismatch
- Further improve error message to allow LLM auto recover better
> fix: improve diffs array error msg

- runtimes/protocol/inlineCompletionWithReferences.ts
https://github.com/aws/language-servers/pull/2011
This is a follow up of the above PR. 
The workspace.getAllTextDocuments() API only returns the open tabs that were clicked during this IDE session. If you open, close, reopen IDE, this API returns empty unless user re-click those files again.
So we need to let IDE compute the list of open tab files and send it to language server
Add open tab params in InlineCompletionWithReferencesParams
> fix: add open tab params to inline completion protocol

- types/chat.ts
The current chat interface lacks support for editing commands/messages after they have been sent. This limits user experience when users need to modify their chat prompts or correct mistakes without starting a new conversation thread.
Added support for message editing by extending the chat type definitions: 
add editable property to ChatMessage and editedText to ButtonClickParams
> feat: editable variable for modify functionality 

- runtimes/README.md
- runtimes/protocol/window.ts
- runtimes/protocol/workspace.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/lsp.ts
- types/window.ts
- types/workspace.ts
No protocol support is available for Flare to get specific files' diagnostics information and open certain files's editors in VSC SIde 
Add the protocol support
- Add CheckDiagnosticsRequestType for checking file diagnostics
- Add openWorkspaceFileRequestType for opening workspace files
- Update base-runtime and standalone to support new LSP methods
- Add type definitions for CheckDiagnosticsParams/Result and OpenWorkspaceFileParams/Result
- Enable language servers to request diagnostic information from IDEs
- Enable language servers to open files in the workspace programmatically
> feat: add diagnostic checking and workspace file opening support

- runtimes/protocol/inlineCompletionWithReferences.ts
Support of inline completion in JL Notebook is gone since the language server migration. 
https://github.com/aws/aws-toolkit-vscode/pull/7086
Let the IDE provide the file context. 
There is a technical limitations of the language server that it cannot find or construct the `vscode.NotebookDocument`, `vscode.NotebookCell`. The `workspace.getTextDocument` does not work with JL Notebook as it gets a URI in the format of "`vscode-notebook-cell:/../A1.ipynb#W2sZmlsZQ%3D%3D`". The language server does not have the cell number, cell state, cursor position, etc of the current cell.
> fix: add file context override for inline completion

- runtimes/runtimes/standalone.ts
No log output for initializeAuth failure
Add a timeout before process kill to ensure the buffer flushes
Tested locally by directly modifying the prod artifact. Note that the webpacked version appears to only output to `stdout` (instead of `stderr`, which should be expected with a `console.error`
> chore: add timeout to ensure error flushes to stdout/err on auth failure

- runtimes/protocol/inlineCompletionWithReferences.ts
- runtimes/runtimes/base-runtime.ts
- runtimes/runtimes/standalone.ts
- runtimes/server-interface/lsp.ts
Part of the work needed to let VS Code IDE get supplemental context from the language server
> feat: add supplemental context api
